# Euler Project Problem 2: Even Fibonacci Numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def fibonacci_sequence():
    fib = []
    a, b = 1, 2

    while b <= 4000000:
        fib.append(a)
        a, b = b, a + b

    return fib

# Generate Fibonacci sequence
fib_sequence = fibonacci_sequence()
print(fib_sequence)

# Find sum of even-valued terms
even_sum = sum(x for x in fib_sequence if x % 2 == 0)
print(f"Sum of even Fibonacci numbers: {even_sum}")
